### ISSUE TITLE
Tried to run ULTRASAT survey, but process gets killed

### ISSUE THREAD

**Issue by AkshayPanayada** [nasa/dorado-scheduling#87]
dorado-scheduling --mission ultrasat --exptime 1200s --nexp 5 --out ex.ecsv -j 8
6.fits
|======================================|   3 /  3  (100.00%)         0s
2023-10-15 00:14:19,892 INFO evaluating field of regard
100%|██████████████████████████████████| 1437/1437 [00:12<00:00, 116.66it/s]
2023-10-15 00:14:37,699 INFO generating model
2023-10-15 00:14:37,727 INFO adding variable: observing schedule
Killed

I was trying to run ultrasat scheduling and this was the error I am recieving. Moreover, the output file is empty

**Comment by lpsinger** [comment]
Would you please attach a copy of 6.fits?

**Comment by lpsinger** [comment]
I bet it's just running out of memory. The `--duration` and `--time-step` options have a big impact on the number of variables and hence the amount of memory required. The default value for `--duration` is 1 orbit and for `--time-step` is 1 minute. Since the model ULTRASAT orbit is a geosynchronous orbit with a period of 1 day, that's 1440 time steps.

Try adding the command line arguments `--time-step 600s --duration 8h` or making other adjustments to reduce the size of the problem.

If that doesn't fix it, then please reopen this issue.
